### ISSUE TITLE
Adding the decimal functionality ,changing the UI .

### ISSUE THREAD

**Issue by soumili19** [Rohan-450/Digiconvert-Calculator#12]
There is no decimal functionality button, and we need to scroll down to see the full calculator

**Comment by Rohan-450** [comment]
Hi, as per the functionality someone already issued the problem and working on it. U can change the UI but it would be easier if they complete the backend first. So wait for a few days . In the mean time explore other projects .

**Comment by soumili19** [comment]
Okay
