### ISSUE TITLE
Adding the *10^x option in the calculator for bigger calculations.

### ISSUE THREAD

**Issue by Arkadipttv** [Rohan-450/Digiconvert-Calculator#13]
![image](https://github.com/Rohan-450/Digiconvert-Calculator/assets/138896045/fb451c2a-831c-49d8-8034-8dd87a0a35d6)

Adding this option will enhance the functionality of the code and also help in faster calculations..
Please, assign this task to me, I want to contribute in this segment.

**Comment by Rohan-450** [comment]
10^x is unnecessary for this kind of binary octal calculations I think.
we dont need this much big calculations for base conversions
