### ISSUE TITLE
Add Functionality to a specific Mode.

### ISSUE THREAD

**Issue by Anos-Voldigoad12** [Rohan-450/Digiconvert-Calculator#18]
Giving all the modes to a single contributor, is not only challenging for the contributor, but also disrupts the distribution of work between the contributors. Therefore, I recommend assigning each mode to a different contributor, whosoever is willing.
I want to contribute to the DEC Mode, but if that's unavailable, I'm willing to take a different Mode, which will be assigned to me.

**Comment by Rohan-450** [comment]
Make the dec mode , can u do it in 1 day?

**Comment by Anos-Voldigoad12** [comment]
Yes

**Comment by Rohan-450** [comment]
You are assigned please sync the forked repo and git pull to update recent changes and make a PR to the testing branch not main

**Comment by Anos-Voldigoad12** [comment]
I created my own branch and made a PR to it. Is that alright? Or do I need to do I need to make PR to the testing branch only?
