### ISSUE TITLE
Fix Mobile View of the website

### ISSUE THREAD

**Issue by Rohan-450** [Rohan-450/Digiconvert-Calculator#2]
the mobile view is distorted. You can fix it

**Comment by rko0211** [comment]
Hey @Rohan-450 i want to work in this issue under Apertre24 kindly assign me this task. Thank you

**Comment by Rohan-450** [comment]
okay I will assign you after 3rd of Jan

**Comment by AnitSarkar123** [comment]
Also, Assign me under Apertre'24

**Comment by Rohan-450** [comment]
Hello @rko0211 are u still down for this issue?
if u are good i will assign it to you on 4th cuz a major backend change will be merged tomorrow it would be better if u work on it after this. Share ur views

**Comment by rko0211** [comment]
Ok no issue..

**Comment by rko0211** [comment]
Hey kindly assign me this task.
![Screen Shot 2024-01-07 at 11 19 48](https://github.com/Rohan-450/Digiconvert-Calculator/assets/97402824/6c00b70b-4445-4a99-8eaf-e66512746d5c)

**Comment by Rohan-450** [comment]
Hello @rko0211 I will assign you this issue
But wait because the UI needs to be changed again. It's better to update the mobile view after the UI is fixed. Thank you

**Comment by rko0211** [comment]
Can you assign me this task now.

**Comment by Rohan-450** [comment]
Hello, u also opened an issue for adding footer, so what will the footer contain ?

**Comment by Rohan-450** [comment]
You are assigned
