### ISSUE TITLE
Make the decimal point useful only once 

### ISSUE THREAD

**Issue by Durgeshwar-AI** [Rohan-450/Digiconvert-Calculator#21]
Like currently the javascript allows the taking of 5.66.4.. any number of decimal to be input in the file i want to fix that such that if a decimal is present in the input any person can't add any extra decimal point to it.

**Comment by Durgeshwar-AI** [comment]
I also would like to make the decimal cell be the initial focus input block.

**Comment by Rohan-450** [comment]
hello @Durgeshwar-AI  ur issue is nice are u referring that after opening the website the default box selected will be of DEC?

**Comment by Durgeshwar-AI** [comment]
> hello @Durgeshwar-AI ur issue is nice are u referring that after opening the website the default box selected will be of DEC?

yes

**Comment by Rohan-450** [comment]
I will issue this to you but after sometime
Need to work with the UI changes now. Make it work in ur local machine till then
1. Usage of decimal(.)only once

**Comment by Rohan-450** [comment]
Just update the decimal point usage to one time
