### ISSUE TITLE
Adding button disability and enability features

### ISSUE THREAD

**Issue by lord-cyclone100** [Rohan-450/Digiconvert-Calculator#3]
I wish to disable all the redundant buttons while working in a particular number system. For example, When you select the binary number system, all buttons from 2-9, A-F would get disabled and so on for other number systems.

**Comment by Rohan-450** [comment]
Okay i will assign you the issue after 3rd jan

**Comment by Rohan-450** [comment]
Hello @lord-cyclone100 U are assigned the issue, Please git pull to update incoming changes

**Comment by lord-cyclone100** [comment]
You got it sir🫡

**Comment by lord-cyclone100** [comment]
I sent the pr. pls check
