### ISSUE TITLE
Want to add a issue template 

### ISSUE THREAD

**Issue by AnitSarkar123** [Rohan-450/Digiconvert-Calculator#37]
Assign me under Aperture'24

**Comment by Rohan-450** [comment]
What is an issue template?

**Comment by AnitSarkar123** [comment]
> What is an issue template?

Issue Templates are issue submission templates you create for commonly addressed issues. They allow you to pre-define appropriate information and values for those issues, such as the Subject, Description of the issue Attachments, etc.

You can encourage contributors to include specific, structured information by using issue forms in your repository about the issue . Issue forms are written in *YAML* using the GitHub form schema.

And if you search any reputed open source project and going to make any issues on this project then this time they give you two option Bug report or Feature request that is made by using issue template
