### ISSUE TITLE
Update the Readme.md file with features and proper screenshots

### ISSUE THREAD

**Issue by Rohan-450** [Rohan-450/Digiconvert-Calculator#4]
write about the project and the problem it solves, different techs used, use images or video for better representation

**Comment by AnitSarkar123** [comment]
Assign me under Apertre'24

**Comment by Rohan-450** [comment]
sure but will assign you but a bit later unless some changes will not be visible

**Comment by Sneha123-zudo** [comment]
Please assign me this issue

**Comment by Sneha123-zudo** [comment]
I'm interested in solving this issue, please assign me this issue

**Comment by abhraneel2004** [comment]
Seems like the issue is still not solved yet. Can you assign It to me PA?
