### ISSUE TITLE
add sound on button click

### ISSUE THREAD

**Issue by YooAshu** [Rohan-450/Digiconvert-Calculator#5]
adding  a click sound on button press would be better
![Screenshot (51)](https://github.com/Rohan-450/Digiconvert-Calculator/assets/95643200/9774fceb-b6c7-49ef-84d7-d097bd1433f3)

**Comment by Rohan-450** [comment]
okay i will assign it to you after 3rd jan

**Comment by dharminnagar** [comment]
I can do it. Assign it to me!

**Comment by Rohan-450** [comment]
Hello @MrGliff as per guidelines I need to assign @YooAshu first for creating this issue. If he somehow fails u will be next. Thanks for understanding. Happy Coding! 😊

**Comment by dharminnagar** [comment]
> Hello @MrGliff as per guidelines I need to assign @YooAshu first for creating this issue. If he somehow fails u will be next. Thanks for understanding. Happy Coding! 😊 

Okaay no problem. But just fyi, I've already solved it. But as you now said, so I'm not creating a PR. Thank you!

**Comment by guddubasu** [comment]
I want to be assigned to this task

**Comment by Rohan-450** [comment]
Hello @YooAshu u up for this issue?

**Comment by YooAshu** [comment]
@Rohan-450  yeah, working on it

**Comment by Rohan-450** [comment]
Try to give soft sounds... not too loud 
Then I am assigning you the issue how many days u need? I can allot you max 2 days

**Comment by Rohan-450** [comment]
Your PR has been merged. Thank You
