### ISSUE TITLE
Feature request : API boxes

### ISSUE THREAD

**Issue by apu52** [Rohan-450/Digiconvert-Calculator#50]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/Rohan-450/Digiconvert-Calculator/assets/114172928/f6a0cbf7-6fb9-42b8-ad2a-5ee3616bdd5d)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@Rohan-450 Please assign me this issue under APERTRE'24

**Comment by Rohan-450** [comment]
In the readme right?

**Comment by apu52** [comment]
> In the readme right?

Yes sir

**Comment by Rohan-450** [comment]
Make the whole readme then with proper pics and information

**Comment by apu52** [comment]
> Make the whole readme then with proper pics and information

Assign the issue to me. I will try to make it
