### ISSUE TITLE
Update the overall UI and add logos or favicons

### ISSUE THREAD

**Issue by Rohan-450** [Rohan-450/Digiconvert-Calculator#6]
update the UI of the calculator to make it more attractive and smooth

**Comment by IndraniSom** [comment]
Assign me in this issue under Apertre-24

**Comment by Rohan-450** [comment]
will assign you after 3rd Jan

**Comment by AnitSarkar123** [comment]
Also ,Assign me under Apertre'24

**Comment by Rohan-450** [comment]
Hello @IndraniSom , hope u are doing well 
as per the guidelines i will be assigning you the issue please pull to update the incoming changes
