### ISSUE TITLE
Adding the conversion functionality between the bases

### ISSUE THREAD

**Issue by Rohan-450** [Rohan-450/Digiconvert-Calculator#9]

**Comment by lord-cyclone100** [comment]
Assign me this job

**Comment by Rohan-450** [comment]
Hello @lord-cyclone100 u are assigned
Please git pull to accept incoming changes

**Comment by lord-cyclone100** [comment]
You got it  sir🫡
Thanks for giving me this oppurtunity
Happy coding😄
